version: '3'
services:
  db:
    image: mysql:latest
    container_name: airport-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456@#
      - MYSQL_DATABASE=airport
    volumes:
      - ~/tools/mysql/db:/var/lib/mysql
